// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCy9ixml_S2J_btYIvw7fiVn0y6Whf5qI',
    appId: '1:385501748004:web:d3fd86f734244fedc9f1b1',
    messagingSenderId: '385501748004',
    projectId: 'moneywise-ai',
    authDomain: 'moneywise-ai.firebaseapp.com',
    storageBucket: 'moneywise-ai.appspot.com',
    measurementId: 'G-GLSRRS1BR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCEcfwnZFG2YzfNZrUKK38nIf0IAWhvJs',
    appId: '1:385501748004:android:40d44e3a9bcbccd2c9f1b1',
    messagingSenderId: '385501748004',
    projectId: 'moneywise-ai',
    storageBucket: 'moneywise-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCoi_IGoVXPTc7Hnbl3P9yzwJ8D27YAPI',
    appId: '1:385501748004:ios:7439d8cd6abe0f66c9f1b1',
    messagingSenderId: '385501748004',
    projectId: 'moneywise-ai',
    storageBucket: 'moneywise-ai.appspot.com',
    iosClientId: '385501748004-u2eovi0td1lalluv6oc266u95h1j2cq8.apps.googleusercontent.com',
    iosBundleId: 'smartm.openalkw.com.smartmoney',
  );
}
